### ISSUE TITLE
Default gulp task does not perform build

### ISSUE THREAD

**Issue by njmcode** [rehabstudio/fe-skeleton#13]
The default `gulp` task activates the watchers but performs no build steps (at least until you save a file).

I think the default task should be to run a full build and exit.  `gulp watch` should be an explicit task that the developer must manually activate.  The idea being that one could pull the repo, run `npm install` then `gulp`, and have the application in a runnable state.

Will PR this later in the week, just putting this here for reference.

**Comment by paddycarey** [comment]
Ideally both `build` and `watch` would be explicit, default can just call one of them but both commands should be available to call.
