### ISSUE TITLE
Static/template HTML output in dist?

### ISSUE THREAD

**Issue by njmcode** [rehabstudio/fe-skeleton#14]
If this skeleton was pulled for a static prototype (say, something to be FTP'd up to some webspace for testing), there is currently no handling for HTML.  Maybe a `templates` or `html` folder that gets copied to `dist` might be an idea?

**Comment by antwan1986** [comment]
Are we wanting to do anything "smart" here like scanning the html file are re-writing script/link resources to be relative to `dist` (hopefully not!), or just literally move the files into dist?

**Comment by duckbox** [comment]
I'm confused.

This plays on the what are the intentions of the repo and its initial destination. Is this meant to be in the root of a projects 'public' folder, or assets folder?

I don't know why we'd be transferring html files into dist, dist is for compiled assets. Static HTML files would preside in the root of the project.

If we had this stage, it would be a good hook for HTML validator, compressor and all that other crap. Minified HTML is something we really ought to do more if we are constantly moaning about page load times.

Back to the point.

_Do we have intentions set on where the skeleton lives in a basic project?_
