### ISSUE TITLE
Remove grunt 

### ISSUE THREAD

**Issue by njmcode** [rehabstudio/fe-skeleton#15]
We've moved past the need for grunt in any new build we do.  I think we can do away with the shared tasks and greatly simplify the `/run` directory now.

**Comment by antwan1986** [comment]
I can certainly action this but I think we'd still need to keep the format of the `/run` directory. Each of those tasks have settings files that are probably better served being external to the corresponding `gulp.js` file as it keeps things future-proof if we were to ever bring another task runner into play.

So in essence, we'd lose the root `gruntfile.js` and all of the `grunt.js` files in the task breakdowns.

**Comment by njmcode** [comment]
I'm cool with this approach, it preserves modularity as you've said elsewhere.
