### ISSUE TITLE
Should RequireJS support be removed?

### ISSUE THREAD

**Issue by antwan1986** [rehabstudio/fe-skeleton#27]
Given that we are going to be looking toward `webpack` for our bundling needs in the near future, I don't see anyone going back to RequireJS anytime soon (I never thought I'd say that).

Removing it would:
* Simplify the `watch` method
* Remove the entire need for the `templates` method (as Browserify does this for us via `hbsfy`).
* Simplify the test suites configuration.
* Remove the need for five or more packages from `package.json`.

**Comment by duckbox** [comment]
I'm surprised you put it in in the first place, but you always where a cautious mare.

Its a witch, burn it!

**Comment by njmcode** [comment]
Yeah, take it out.  Async bundling via Webpack or a Browserify lib will take care of the need for this.
