### ISSUE TITLE
Reduce gulp task structure complexity

### ISSUE THREAD

**Issue by grieve** [rehabstudio/fe-skeleton#39]
With the removal of alternate task runners, do each of the gulp tasks require the `_common.js`/`gulp.js` duo, wouldn't this be simpler to replace with one file per task.

```
run/tasks/scripts/
...  _common.js
...  gulp.js
run/tasks/styles/
...  _common.js
...  gulp.js
```

becomes

```
run/tasks/scripts.js
run/tasks/styles.js
```

**Comment by antwan1986** [comment]
As discussed a while ago on Slack, the `_common` files do still serve a purpose of housing the tasks settings and keeping them isolated away from some of the bigger tasks. There's also some upcoming tasks such as a webpack task that will have more than one file associated with it, and the folder structure gives us the flexibility to group associated files together.

**Comment by grieve** [comment]
Could there be a middle ground here, where we rename the main file in each task from `gulp.js` to `index.js`? That way tasks are imported like `require('./run/tasks/scripts')` and that can be either a single file named `scripts.js` or a directory like `scripts/index.js`.

**Comment by antwan1986** [comment]
Absolutely. The fact they're named `gulp.js` is a hang over from whenever we also had `grunt.js` files.
