### ISSUE TITLE
Implement browsersync into server build

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [rehabstudio/fe-skeleton#47]
Keep it simple, few options, simple css injection and reloading after scripts.

```browsersync.reload()``` in gulp pipe after dest.

http://www.browsersync.io/

**Comment by MickCoelho** [comment]
What about the Webpack "hot module replacement"?
https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack

**Comment by theboyWhoCriedWoolf** [comment]
Hot module replacement adds a lot of overhead if you are not using webpack to load in css files.

https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack#caveats

**Comment by antwan1986** [comment]
Completed with #98 !
