### ISSUE TITLE
Use Webpack as module system, compiler and minifier

### ISSUE THREAD

**Issue by njmcode** [rehabstudio/fe-skeleton#49]
Webpack has been tested enough internally to be roadworthy at this point.  It will handle our CommonJS bundling (with the much-needed multi-bundling included), our CSS and JS compilation and uglifying.

We can remove a lot of the devDependencies in `package.json` with this, including Browserify and our CSS/JS deps, and get the bloat down.

**Comment by MickCoelho** [comment]
Might be interesting to use the "hot loader" as well: 
https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack

So, we're solving issue #47 as well ( https://github.com/rehabstudio/fe-skeleton/issues/47 )
