### ISSUE TITLE
Plans for implementing JS style checking?

### ISSUE THREAD

**Issue by antwan1986** [rehabstudio/fe-skeleton#5]
I came across this today and thought it might be a good thing to include into the toolchain. The only downside I can think of is that it might be time consuming for us to write the rules we require.

JSCS:
http://jscs.info/overview.html

**Comment by duckbox** [comment]
I'd have thought something like this maybe better presented in our editors like ST3 ?

**Comment by antwan1986** [comment]
There's plugins for ST3 that can load in settings files, just like our EditorConfig file

**Comment by paddycarey** [comment]
It's good to have in your editor so you can see/fix things as you go, but there should be a check in the build toolchain too, something that's not easily ignored or missed by those using different editors.

I don't think it'd be time consuming at all to maintain, you'd only be defining places where you differ from the defaults of whatever tool you're using, choose wisely and that might only be 10-20 rules max. Set once and forget, have a quick check whenever you bump the version of the linting tool in the skeleton.

**Comment by antwan1986** [comment]
Additional Info:

https://github.com/jscs-dev/gulp-jscs
https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/Resources/settings-defaults/.jscsrc
