### ISSUE TITLE
[to-do] Cloning

### ISSUE THREAD

**Issue by duckbox** [rehabstudio/fe-skeleton#6]
Need a segment in the docs for cloning the repo, if its to be the base of a project. Also information on how to change a repositories url and safely remove fe-skeletons maybe beneficial for those not in the know.

**Comment by antwan1986** [comment]
By this you mean a paragraph on how to delete the `.git` folder which would leave you free to `git init` as a whole new project, right?

**Comment by paddycarey** [comment]
I don't think we should be encouraging people to delete `.git`, simply changing the origin remote would preserve the history which IMO is very valuable
