### ISSUE TITLE
Updated .gitignore, seems old and maybe redundant

### ISSUE THREAD

**Issue by grieve** [rehabstudio/fe-skeleton#81]
Best to use an auto generated one from gitignore.io or similar, with our specific additions on top

**Comment by antwan1986** [comment]
Good shout; I didn't even know this site existed. Seems pretty sweet! At first glance I'm assuming something along these lines would suffice?

https://www.gitignore.io/api/appengine%2Cdjango%2Cgrunt%2Cnode%2Clinux%2Cpython%2Csass%2Cwindows%2Cvim

**Comment by grieve** [comment]
Yep. Add `osx` and `sublimetext` and no need to the first two sections there

`https://www.gitignore.io/api/appengine,django,grunt,node,linux,python,sass,windows,vim,osx,sublimetext`

```
# JavaScript maps
*.js.map

# Sphinx env artifacts
docs/_build/doctrees/environment.pickle

# Output by junit/cobertura via Karma for integration with Jenkins.
fe-test-results.xml
fe-coverage-results.xml

# Default destination for image minification.
img-min
```
